[tool.poetry]
name = "sheet-to-triples"
license = "GPL-3.0-or-later"
version = "0.1.0"
authors = ["Martin Packman <martin.packman@visual-meaning.com>"]
description = "Convert tabular data into triples."

[tool.poetry.dependencies]
python = "^3.11"
pycountry = "^20"
openpyxl = "^3"
rdflib = {version = "^7.0.0", extras = ["sparql"]}
xlrd = "^1"

[tool.poetry.dev-dependencies]
ruff = "^0.0.253"
coverage = "^5.5"
pyfakefs = "^4.5"

[tool.ruff]
select = ["C9", "E", "F", "W"]
